### ISSUE TITLE
Credits section in readme

### ISSUE THREAD

**Issue by nikoksr** [kha7iq/pingme#39]
Hey @kha7iq, I remember you once contributed to [notify](https://github.com/nikoksr/notify); thanks again for that and congratulations for your great and successful project here!

I stumbled across your project through [godoc](https://pkg.go.dev/github.com/nikoksr/notify?tab=importedby) and to be honest was a bit irritated that you took parts of the readme from notify (which is perfectly fine) but *explicitly* removed the [Credits](https://github.com/nikoksr/notify#credits-) section. Like your project, notify stands on the shoulders of giants and the least we can do is give credit to those projects. Of course you can't credit every single project but if a project like yours (pingme) is based to such a large extent on a single project ([notify](https://github.com/nikoksr/notify)) then we would be very grateful if you would at least credit us in your readme; especially since you yourself are part of the [notify contributors](https://github.com/nikoksr/notify/graphs/contributors).

Best regards and happy coding!

**Comment by kha7iq** [comment]
Hello @nikoksr 
Ofcource this project is based on your library and this fact is mentioned in multiple issues like https://github.com/kha7iq/pingme/issues/17 so i don't think there was any intention of hiding this fact.

The library you created is great thats why i contributed to it as well. i have no problem adding the credits to readme and honestly i did not expected the project to have this much success. :) 
I will update the readme and add credits.
Cheers

**Comment by kha7iq** [comment]
Done.
Readme is now updated with credits.
