### ISSUE TITLE
Arch Linux AUR package

### ISSUE THREAD

**Issue by kugland** [kha7iq/pingme#53]
I have created a AUR package that builds from the sources, it’s called `pingme`.

Please add it to the README.md.

**Comment by kha7iq** [comment]
Thank you @kugland. 
I will add it to the readme, i hope it will stay up to date with new version.
Let me know if you need help with that in future, i can add to to auto release.

**Comment by kugland** [comment]
I can add you as a maintainer, if you’d like, @kha7iq .

**Comment by kha7iq** [comment]
> I can add you as a maintainer, if you’d like, @kha7iq .

That will be very much appreciated, i can add my own ssh key to automated release in that case.

**Comment by kugland** [comment]
> > I can add you as a maintainer, if you’d like, @kha7iq .
> 
> That will be very much appreciated, i can add my own ssh key to automated release in that case.

Done.
