### ISSUE TITLE
Can't send email without password

### ISSUE THREAD

**Issue by BrunIF** [kha7iq/pingme#56]
**Describe the bug**

2021/08/03 11:44:41 failed to send mail: smtp: server doesn't support AUTH: send notification
**To Reproduce**

1. send email without (empty) password

- OS: Ubuntu
- Version 0.2.3

**Comment by kha7iq** [comment]
Thanks for opening the issue. 
Can you describe the issue in details, i need more information about this.
> 1. send email without (empty) password
Do you mean to say you can not send email when exporting the password via env var ? 


```bash
pingme email \
  --rec "example@gmail.com" \
  --msg "This is an email from PingMe CLI" \
  --sub "Email from PingMe CLI" \
  --sender "sender@gmail.com" \
  --host "smtp.gmail.com" \
  --port "587" \
  --pass "secretPassword"
```
If you don't want to specify the password with `--pass` then you can export it via variable EMAIL_PASSWORD.

**Comment by BrunIF** [comment]
In my case, I can put any email, but the password does not have to be. I don't know how you could reproduce it. Can this option be made optional?

**Comment by kha7iq** [comment]
`Email` uses your existing email provider to send emails, in this example it uses server settings for gmail.
For example if you send an email to me you have to provide your `gmail` account and pass to `pingme`, then it will use that account to send emails.
You can input my email with `--rec` flag and proceed.

**Comment by BrunIF** [comment]
![image](https://user-images.githubusercontent.com/490917/129197890-4449a9e7-151c-4a5f-be38-78643e73701e.png)

**Comment by kha7iq** [comment]
@BrunIF I understand the issue now.
pingme uses `https://pkg.go.dev/net/smtp#PlainAuth` for email, i have set the password to optional in [new branch](https://github.com/kha7iq/pingme/tree/disable-require-flag-for-email) can you please build it locally and test.
Let me know if it works for you and i will merge it to master afterwards.

```bash
git clone -b disable-require-flag-for-email https://github.com/kha7iq/pingme.git
cd pingme
go build -o pingme main.go
./pingme .......
```

**Comment by BrunIF** [comment]
Not working. 
Most likely this problem is not pingme.
