### ISSUE TITLE
Support for carriage return \n

### ISSUE THREAD

**Issue by matbgn** [kha7iq/pingme#60]
**Is your feature request related to a problem? Please describe.**

I was not able to send a msg (for instance via teams) with carriage return in it (\n Linux). Is there a way to achieve it?

**Describe the solution you'd like**

Sending a msg in form of:
`pingme teams -w TOKEN --msg "Hi, I got a**\n** carriage return. Nice!"`

**Describe alternatives you've considered**

Over ways to pass it will be totally acceptable

**Additional context**

**PingMe version 0.2.4**
NAME="Linux Mint"
VERSION="20.2 (Uma)"
ID=linuxmint
ID_LIKE=ubuntu

A great thank you for you're implementation of [nikoksr](https://github.com/nikoksr)/[notify](https://github.com/nikoksr/notify)!

**Comment by kha7iq** [comment]
Hello @matbgn , 
The whole messages is treated as a string, i am afraid it won't be possible to achieve this when sending message. 
You can use the `--title` flag when sending a message it will add '\n' between the tittle and message.

```bash
pingme teams -w TOKEN --title "Hi, I got a"  --msg  "carriage return. Nice!"
```

**Comment by matbgn** [comment]
Again  juste thank you!

What would be the adaptations necessary to make it work? Could you point me any direction, so I could maybe invest some time to make a PR?

**Comment by kha7iq** [comment]
One way would be to analyze the content of message before sending it , check for specified carriage return using regex maybe. 
Then recreate the string again, its a messy solution and too many things to consider when implementing it not sure if its worth spending time on it. 
You can [have a look here](https://github.com/kha7iq/pingme/blob/master/service/mattermost/mattermost.go#L140) how its being added for title and message. 

You are welcome, and i hope you find it useful.

**Comment by matbgn** [comment]
Oh nice it sounds that it's in my possibilities :smile: 

But still a question, you pointed me out on [service/mattermost/mattermost.go](https://github.com/kha7iq/pingme/blob/0e2992e4aa4c809809ab0388ce85047d745c0e5f/service/mattermost/mattermost.go) but my issue is on Microsoft Teams :thinking: and I see two other services implemented with it (Twilio and Mastodon). What should I take care of?

**Comment by kha7iq** [comment]
Mattermost was just an example , and because it not using notify you can see how message is constructed. 
But [teams ](https://github.com/kha7iq/pingme/blob/master/service/msteams/msteams.go#L74)and quite a few other services use `notify`, so this implementation has to be on notify side.

**Comment by matbgn** [comment]
I will take care of it on August due to work load but it's on my todo list :wink:
