### ISSUE TITLE
feat(service): add support for matrix server

### ISSUE THREAD

**Issue by matbgn** [kha7iq/pingme#61]
[Matrix](https://www.matrix.org/) is free and open source self hosted service. Adding it to the supported push services will be useful.

It's the back-end part of the formerly known Riot.im know called [Element](https://element.io/)

**Describe the solution you'd like**

Server has an api which can be used to send messages.

**Additional context**

Some useful links:

- [Matrix API Documentation](https://matrix.org/docs/guides/client-server-api)
- [Gist using Curl to communicate with matrix](https://gist.github.com/RickCogley/69f430d4418ae5498e8febab44d241c9)

**Comment by matbgn** [comment]
The detailed structure looks like this:

```
curl -XPOST -d '{"msgtype":"m.text", "body":"TEXT_MESSAGE_TO_BE_SENT"}' "https://MATRIX_SERVER_URL/_matrix/client/r0/rooms/%21ROOM_IDENTIFIER:DOMAIN_URL/send/m.room.message?access_token=USER_ACCESS_TOKEN
```

e.g. for ENVs:
- TEXT_MESSAGE_TO_BE_SENT="Hello"
- MATRIX_SERVER_URL="matrix.example.com"
- ROOM_IDENTIFIER="nRSNvEQVyMBIkIJPTc" # Without exclamation mark !, in curl command replaced by %21
- DOMAIN_URL="example.com"
- USER_ACCESS_TOKEN="syt_XXXXXXXX_YYYYYYYYYYYYYYYYYYYY_ZZZZZZ"

Hope that helps

**Comment by ahdekkers** [comment]
I'd be happy to work on this issue

**Comment by kha7iq** [comment]
@ahdekkers
You can assign the issue to your self.
let me know if anything i can assist with.

**Comment by ahdekkers** [comment]
Ok, thanks. Sorry but I'm a bit new to the whole open source contributing business, and not sure how to assign myself :) If you could let me know how to do that, that would be helpful - will get started on this in the meantime anyway, @kha7iq.

**Comment by kha7iq** [comment]
I am glad that you have chosen to dedicate some time for this project, i have assigned the issue to you. 
Just ask in the task if you need anything.
