### ISSUE TITLE
feat(service): add support for whatsapp

### ISSUE THREAD

**Issue by matbgn** [kha7iq/pingme#62]
Adding Whatsapp will be absolutely awesome.

**Describe the solution you'd like**

Based on the Notify service would it be possible to do this without huge work?
https://github.com/nikoksr/notify/tree/main/service/whatsapp

**Comment by kha7iq** [comment]
Closing this as its not possible with current implementation whatsapp with Notify.

**Comment by matbgn** [comment]
Seeing all pour inputs, what will be the requirements to make it happen?

In other words what would be the macro steps to link PingMe CLI > Notify > WhatsApp ?

**Comment by kha7iq** [comment]
A PR was already opened by Kristina Kupreeva, untill the issue with whatsapp API is not fixed neither directly nor with Notify we can implement this. 
Have a look at the comment here : https://github.com/kha7iq/pingme/pull/63#issuecomment-1097639689

**Comment by matbgn** [comment]
Thank you for your quick answer. Did notice Kristina's work but wasn't really sure of were layed the problem at the end. Seems clearer now, so we just have to be patient or take a look at this API implementation.

**Comment by matbgn** [comment]
Is there any chance to bridge PingMe directly with the Go library proposed as replacement? Or are we strongly binded with Notify?

> Warning
This package is not being actively maintained currently and will soon be unusuable as WhatsApp updates to multi-device. Please look at [tulir/whatsmeow](https://github.com/tulir/whatsmeow) for a Go WhatsApp Web API that is actively maintained and supports WhatsApp multi-device.

**Comment by kha7iq** [comment]
It is possible we already have a few services which do not use notify for integration.

**Comment by matbgn** [comment]
OK thanks, good to know for the future also. In the mean time Niko Köser  from Notify responded to my question about switching to another WhatsApp library. It seems that it is on his highest priority list, so we will first wait a few months before going any further:

> [@matbgn](https://github.com/matbgn) thank you very much for the report! And sorry for the inconvenience. I definitely want to keep the WhatsApp service alive, so I or someone else will take care of it as soon as possible.

https://github.com/nikoksr/notify/issues/274#issuecomment-1123576029
