### ISSUE TITLE
Ability to send messages to users (not channels) in rocket chat

### ISSUE THREAD

**Issue by lconcha** [kha7iq/pingme#71]
pingme is fantastic! 

In addition to being able to send messages to rocket chat channels, it would be great to be able to send messages to specific users. However, I can't find a way to do it, or it is not implemented yet. 

I would like to:

```
pingme --channel user --msg "hi!" --token $TOKEN --userid $MYUSER --url $URL
```

Thanks!

**Comment by kha7iq** [comment]
Thank you @lconcha 
Only sending messages to channels is supported.  The library used to send messages only supports this, adding functionality for individual users means that we have to rewrite this service separately.
