### ISSUE TITLE
gzip error when installing

### ISSUE THREAD

**Issue by githubxnoob** [kha7iq/pingme#75]
**Describe the bug**
i am trying to install it on raspberry pi 4 but i get the following error 
```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
**To Reproduce**

```
curl -s https://raw.githubusercontent.com/kha7iq/pingme/master/install.sh | sudo sh
Fetching latest version
Found version 0.2.6
Downloading pingme_0.2.6_Linux_aarch64.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Expected behavior**

**successful installation**

**Desktop (please complete the following information):**

- OS: raspberry pi os 64 bit (ARM64)
- Version: Debian GNU/Linux 11 (bullseye)

**Comment by kha7iq** [comment]
@githubxnoob 
The install script is fixed now, can you try again and let me know if this fixed your issue.
